//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;

    public partial class tblKhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKhachHang()
        {
            this.tblPhieuDatPhongs = new HashSet<tblPhieuDatPhong>();
            this.tblTinNhans = new HashSet<tblTinNhan>();
        }
        [Required(ErrorMessage = "Vui lòng nhập tài khoản")]
        public string ma_kh { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "Vui lòng bao gồm kí tự đặc biệt , chữ in hoa")]
        public string mat_khau { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ tên")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Vui lòng nhập họ tên thật")]
        public string ho_ten { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số chứng minh thư")]
        [StringLength(12, MinimumLength = 9, ErrorMessage = "Vui lòng nhập số chứng minh thư thật")]
        public string cmt { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Vui lòng nhập số điện thoại thật")]
        public string sdt { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Vui lòng nhập email thật")]
        public string mail { get; set; }
        public Nullable<int> diem { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuDatPhong> tblPhieuDatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTinNhan> tblTinNhans { get; set; }
    }
}
